/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneoTenis_Vistas;

import javax.swing.JOptionPane;
import torneoTenis_Data.EstadioData;
import torneotenis.Conectar;
import torneotenis.Estadio;

/**
 *
 * @author Familia
 */
public class VistaEstadio extends javax.swing.JInternalFrame {
    private EstadioData estadioData;
    private Conectar conn;
    

    /**
     * Creates new form VistaEstadio
     */
    public VistaEstadio() {
        initComponents();
         conn = new Conectar();
        estadioData = new EstadioData(conn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCiudad = new javax.swing.JTextField();
        jtAncho = new javax.swing.JTextField();
        jtLargo = new javax.swing.JTextField();
        jtDireccion = new javax.swing.JTextField();
        jcbCategoria = new javax.swing.JComboBox<>();
        jtCapacidad = new javax.swing.JTextField();
        jchbActivo = new javax.swing.JCheckBox();
        jchbHabilitado = new javax.swing.JCheckBox();
        jbBuscar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();

        jCheckBox2.setText("jCheckBox2");

        jButton3.setText("jButton3");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ESTADIO");

        jLabel2.setText("ID Estadio:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Ciudad:");

        jLabel5.setText("Ancho:");

        jLabel6.setText("Largo:");

        jLabel7.setText("Categoría:");

        jLabel8.setText("Habilitado:");

        jLabel9.setText("Dirección:");

        jLabel10.setText("Capacidad:");

        jLabel11.setText("Activo");

        jtId.setEditable(false);

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jtAncho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAnchoFocusLost(evt);
            }
        });

        jtLargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtLargoFocusLost(evt);
            }
        });

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Césped", "Ladrillo", "Cemento" }));

        jtCapacidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCapacidadFocusLost(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchbActivo)
                                            .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtNombre)
                                            .addComponent(jtCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addComponent(jbBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(45, 45, 45)
                                .addComponent(jbActualizar)
                                .addGap(52, 52, 52)
                                .addComponent(jbEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchbHabilitado)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jbLimpiar))
                    .addComponent(jtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jchbHabilitado))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jchbActivo)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbActualizar)
                    .addComponent(jbEliminar)
                    .addComponent(jbLimpiar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:

        String nombre = jtNombre.getText();
        Estadio estadio = estadioData.buscarEstadio(nombre);
        
        if(estadio != null){
            jtId.setText(estadio.getId_estadio()+"");
            jtNombre.setText(estadio.getNombre()+"");
            jtCiudad.setText(estadio.getCiudad()+"");
            jtAncho.setText(estadio.getAncho()+"");
            jtLargo.setText(estadio.getLargo()+"");
            jcbCategoria.setSelectedItem(estadio.getCategoria()+"");
            jchbHabilitado.setSelected(estadio.isHabilitado());
            jtDireccion.setText(estadio.getDireccion()+"");
            jtCapacidad.setText(estadio.getCapacidad()+"");
            jchbActivo.setSelected(estadio.isActivo());
            jbGuardar.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(this,"No se encontraron datos");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        if (jtNombre.getText().isEmpty() ||jtCiudad.getText().isEmpty()||jtAncho.getText().isEmpty()||
                jtLargo.getText().isEmpty()||jtDireccion.getText().isEmpty()||jtCapacidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Completar campos");
        }   
        else {
        String nombre = jtNombre.getText();
        String ciudad = jtCiudad.getText();
        float ancho = Float.parseFloat(jtAncho.getText());
        float largo = Float.parseFloat(jtLargo.getText());
        String categoria = (String) jcbCategoria.getSelectedItem();
        boolean habilitado = jchbHabilitado.isEnabled();
        String direccion = jtDireccion.getText();
        int capacidad = Integer.parseInt(jtCapacidad.getText());
        boolean activo=jchbActivo.isEnabled();
        
        Estadio estadio = new Estadio(nombre, ciudad, ancho, largo, categoria, habilitado, direccion, capacidad, activo);
        estadioData.guardarEstadio(estadio);
        jtId.setText(estadio.getId_estadio()+"");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        if(jtId.getText()!=null){
          if (jtNombre.getText().isEmpty() ||jtCiudad.getText().isEmpty()||jtAncho.getText().isEmpty()||
                jtLargo.getText().isEmpty()||jtDireccion.getText().isEmpty()||jtCapacidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Completar campos");
        }   
        else {
            int id_estadio=Integer.parseInt(jtId.getText());
            String nombre = jtNombre.getText();
            String ciudad = jtCiudad.getText();
            float ancho = Float.parseFloat(jtAncho.getText());
            float largo = Float.parseFloat(jtLargo.getText());
             String categoria = (String) jcbCategoria.getSelectedItem();
             boolean habilitado = jchbHabilitado.isEnabled();
            String direccion = jtDireccion.getText();
            int capacidad = Integer.parseInt(jtCapacidad.getText());
            boolean activo = jchbActivo.isEnabled();
        
            Estadio estadio = new Estadio(id_estadio, nombre, ciudad, ancho, largo, categoria, habilitado, direccion, capacidad, activo);
            estadioData.actualizarEstadio(estadio);
        }}else{
            JOptionPane.showMessageDialog(this,"No se encontraron datos");
        }
        
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
         int id_estadio = Integer.parseInt(jtId.getText());
        estadioData.borrarEstadio(id_estadio);
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        jtId.setText("");
        jtNombre.setText("");
        jtCiudad.setText("");
        jtAncho.setText("");
        jtLargo.setText("");
        jchbHabilitado.setSelected(false);
        jtDireccion.setText("");
        jtCapacidad.setText("");
        jchbActivo.setSelected(false);
        jcbCategoria.setSelectedIndex(0);
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jtAnchoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAnchoFocusLost
        // TODO add your handling code here:
        try {
            float ancho = Float.parseFloat(jtAncho.getText());
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Usted ingresó un digito incorrecto");
            jtAncho.requestFocus();
        }
    }//GEN-LAST:event_jtAnchoFocusLost

    private void jtLargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtLargoFocusLost
        // TODO add your handling code here:
        try {
            float largo = Float.parseFloat(jtLargo.getText());
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Usted ingresó un digito incorrecto");
            jtLargo.requestFocus();
        }
    }//GEN-LAST:event_jtLargoFocusLost

    private void jtCapacidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCapacidadFocusLost
        // TODO add your handling code here:
        try {
            int capa = Integer.parseInt(jtCapacidad.getText());
            if(capa < 2000 || capa > 20000){
                JOptionPane.showMessageDialog(this, "La capacidad debe ser entre 2000 y 20000");
        }} catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Usted ingresó un digito incorrecto");
            jtCapacidad.requestFocus();
        }
    }//GEN-LAST:event_jtCapacidadFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JCheckBox jchbActivo;
    private javax.swing.JCheckBox jchbHabilitado;
    private javax.swing.JTextField jtAncho;
    private javax.swing.JTextField jtCapacidad;
    private javax.swing.JTextField jtCiudad;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtLargo;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
