/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneoTenis_Vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import torneoTenis_Data.JugadorData;
import torneoTenis_Data.PatrocinioData;
import torneoTenis_Data.SponsorData;
import torneotenis.Conectar;
import torneotenis.Jugador;
import torneotenis.Patrocinio;
import torneotenis.Sponsor;

/**
 *
 * @author Familia
 */
public class VistaSponsorPatrocinio extends javax.swing.JInternalFrame {
    private SponsorData sponsorData;
    private PatrocinioData patrocinioData;
    private Conectar conn;
    private JugadorData jd;
    private ArrayList<Jugador> listaJugadores;
    private ArrayList<Sponsor> listaSponsor;

    /**
     * Creates new form VistaSponsorPatrocinio
     */
    public VistaSponsorPatrocinio() {
        initComponents();
        conn = new Conectar();
        sponsorData = new SponsorData(conn);
        jd = new JugadorData(conn);
        patrocinioData = new PatrocinioData(conn);
        cargarJugadores();
        cargarSponsors();
    }

    public void cargarJugadores(){
        List<Jugador> jugadores = jd.listaDeJugadores();
        for(Jugador ju: jugadores){
            jcbJugador.addItem(ju);
        }
    }
    
    public void cargarSponsors(){
        List<Sponsor> sponsors = sponsorData.listaDeSponsors();
        for(Sponsor s: sponsors){
            jcbSponsor.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 1), new java.awt.Dimension(0, 1), new java.awt.Dimension(32767, 1));
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtIdSpon = new javax.swing.JTextField();
        jtMarca = new javax.swing.JTextField();
        jtIndumentaria = new javax.swing.JTextField();
        jchbActivo = new javax.swing.JCheckBox();
        jbGuardarSpon = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbEliminarSpon = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcbJugador = new javax.swing.JComboBox<>();
        jtIdPat = new javax.swing.JTextField();
        jcbSponsor = new javax.swing.JComboBox<>();
        jbGuardarPat = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jchbActivoP = new javax.swing.JCheckBox();
        jbBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("SPONSOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("PATROCINIO");

        jLabel3.setText("ID Sponsor:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Indumentaria:");

        jLabel6.setText("Activo");

        jtIdSpon.setEditable(false);

        jbGuardarSpon.setText("Guardar Sponsor");
        jbGuardarSpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarSponActionPerformed(evt);
            }
        });

        jbActualizar.setText("Actualizar Sponsor");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbEliminarSpon.setText("Eliminar");
        jbEliminarSpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarSponActionPerformed(evt);
            }
        });

        jLabel7.setText("ID Patrocinio:");

        jLabel8.setText("Sponsor:");

        jLabel9.setText("Jugador:");

        jtIdPat.setEditable(false);

        jbGuardarPat.setText("Firmar Contrato");
        jbGuardarPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarPatActionPerformed(evt);
            }
        });

        jLabel10.setText("Activo");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtIdSpon)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jchbActivo)
                                .addComponent(jtIndumentaria))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbGuardarSpon)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jbBuscar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbEliminarSpon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbActualizar))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jtIdPat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchbActivoP)
                                            .addComponent(jcbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 83, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addContainerGap(319, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbGuardarPat)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtIdSpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtIdPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcbSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtIndumentaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jchbActivo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jchbActivoP))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbGuardarSpon)
                            .addComponent(jbActualizar))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGuardarPat)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbEliminarSpon)
                    .addComponent(jbBuscar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarSponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarSponActionPerformed
        // TODO add your handling code here:
        String marca = jtMarca.getText();
        String indumentaria = jtIndumentaria.getText();
        boolean activo=jchbActivo.isEnabled();
        
        Sponsor sponsor = new Sponsor(marca, indumentaria, activo);
        sponsorData.guardarSponsor(sponsor);
        jtIdSpon.setText(sponsor.getId_sponsor()+"");
        
    }//GEN-LAST:event_jbGuardarSponActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        if(jtIdSpon.getText()!=null){
            int id_sponsor=Integer.parseInt(jtIdSpon.getText());
            String marca = jtMarca.getText();
            String indumentaria = jtIndumentaria.getText();
            boolean activo = jchbActivo.isEnabled();
        
            Sponsor sponsor = new Sponsor(id_sponsor, marca, indumentaria, activo);
            sponsorData.actualizarSponsor(sponsor);
        }else{
            JOptionPane.showMessageDialog(this,"No se encontraron datos");
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbEliminarSponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarSponActionPerformed
        // TODO add your handling code here:
        int id_sponsor = Integer.parseInt(jtIdSpon.getText());
        sponsorData.borrarSponsor(id_sponsor);
    }//GEN-LAST:event_jbEliminarSponActionPerformed

    private void jbGuardarPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarPatActionPerformed
        // TODO add your handling code here:
        Sponsor sponsor = (Sponsor) jcbSponsor.getSelectedItem();
        Jugador jugador = (Jugador) jcbJugador.getSelectedItem();
        boolean activo = jchbActivoP.isEnabled();
        
        Patrocinio patrocinio = new Patrocinio(sponsor, jugador, true);
        patrocinioData.guardarPatrocinio(patrocinio);
        jtIdPat.setText(patrocinio.getId_patrocinio()+ "");
        
    }//GEN-LAST:event_jbGuardarPatActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        //int id_sponsor = Integer.parseInt(jtIdSpon.getText());
        String marca = jtMarca.getText();
        String indumentaria = jtIndumentaria.getText();
        Sponsor sponsor = sponsorData.buscarSponsor(marca, indumentaria);
        
        if (sponsor != null){
            jtIdSpon.setText(sponsor.getId_sponsor() + "");
            jtMarca.setText(sponsor.getMarca() + "");
            jtIndumentaria.setText(sponsor.getIndumentaria() + "");
            jchbActivo.setSelected(sponsor.isActivo());
        }else{
            JOptionPane.showMessageDialog(this, "No hay Sponsor con esos datos");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminarSpon;
    private javax.swing.JButton jbGuardarPat;
    private javax.swing.JButton jbGuardarSpon;
    private javax.swing.JComboBox<Jugador> jcbJugador;
    private javax.swing.JComboBox<Sponsor> jcbSponsor;
    private javax.swing.JCheckBox jchbActivo;
    private javax.swing.JCheckBox jchbActivoP;
    private javax.swing.JTextField jtIdPat;
    private javax.swing.JTextField jtIdSpon;
    private javax.swing.JTextField jtIndumentaria;
    private javax.swing.JTextField jtMarca;
    // End of variables declaration//GEN-END:variables
}
