/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneoTenis_Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import torneoTenis_Data.JugadorData;
import torneoTenis_Data.PatrocinioData;
import torneoTenis_Data.SponsorData;
import torneotenis.Conectar;
import torneotenis.Jugador;
import torneotenis.Patrocinio;
import torneotenis.Sponsor;

/**
 *
 * @author Administrador
 */
public class VistaJugadoresXSponsor extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private Conectar conn;
    private JugadorData jugador;
    private PatrocinioData pat;
    private SponsorData sponsor;
    private ArrayList<Jugador> listaJugadores;
    private ArrayList<Sponsor> listaSponsor;

    /**
     * Creates new form VistaJugadoresXSponsor
     */
    public VistaJugadoresXSponsor() {
        initComponents();
        conn = new Conectar();
        jugador = new JugadorData(conn);
        sponsor = new SponsorData(conn);
        pat = new PatrocinioData(conn);
        Patrocinio p = new Patrocinio();
        listaSponsor = (ArrayList) sponsor.listaDeSponsors();
        
        armarCabeceraTabla();
        cargarSponsors();
        cargarDatos();
    }
    public void armarCabeceraTabla() {
        jtJugadores.getTableHeader().setReorderingAllowed(false);
        
        ArrayList<Object> columnas = new ArrayList<Object>();
        
        columnas.add("ID");
        columnas.add("Nombre");
        columnas.add("DNI");

        
        for (Object it: columnas) {
            modelo.addColumn(it);
        }
        jtJugadores.setModel(modelo);
    }
    
    public void cargarSponsors() {
        
        for(Sponsor item: listaSponsor) {
            jcbSponsor.addItem(item);
        }
    } 
     public void borrarFilasTabla() {
        int a = modelo.getRowCount()-1;
        
        for(int i=a; i>=0; i--) {
            modelo.removeRow(i);
        }
    }
     
    public void cargarDatos() {
          
        borrarFilasTabla();
        
        Sponsor s = (Sponsor)jcbSponsor.getSelectedItem();
        listaJugadores = (ArrayList)pat.obtenerJugadoresXSponsor(s.getId_sponsor());

        for (Jugador j: listaJugadores){
            modelo.addRow(new Object[] {j.getId_jugador(), j.getNombreApellido(), j.getDni()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbSponsor = new javax.swing.JComboBox<>();
        jlSponsor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtJugadores = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Jugadores por Sponsor");

        jcbSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSponsorActionPerformed(evt);
            }
        });

        jlSponsor.setText("Sponsor");

        jtJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtJugadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jlSponsor)
                        .addGap(18, 18, 18)
                        .addComponent(jcbSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSponsor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSponsorActionPerformed
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jcbSponsorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Sponsor> jcbSponsor;
    private javax.swing.JLabel jlSponsor;
    private javax.swing.JTable jtJugadores;
    // End of variables declaration//GEN-END:variables
}
