/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneoTenis_Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import torneoTenis_Data.EncuentrosData;
import torneoTenis_Data.JugadorData;
import torneoTenis_Data.TorneoData;
import torneotenis.Conectar;
import torneotenis.Jugador;
import torneotenis.Torneo;

/**
 *
 * @author Administrador
 */
public class VistaJugadoresXTorneo extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private EncuentrosData enc;
    private TorneoData tor;
    private JugadorData jugador;
    private Conectar conn;
    private ArrayList<Torneo> listaTorneos;
    private ArrayList<Jugador> listaJugadores;

    /**
     * Creates new form VistaJugadoresXTorneo
     */
    public VistaJugadoresXTorneo() {
        initComponents();

        conn = new Conectar();
        enc = new EncuentrosData(conn);
        tor = new TorneoData(conn);
        jugador = new JugadorData(conn);
        Torneo t = new Torneo();
        listaTorneos = (ArrayList) tor.listaDeTorneos();
       
        
        
        armarCabeceraTabla();
        cargarTorneos();
        
    }
    
    public void armarCabeceraTabla() {
        jtJugadores.getTableHeader().setReorderingAllowed(false);
        
        ArrayList<Object> columnas = new ArrayList<Object>();
        
        columnas.add("ID");
        columnas.add("Nombre Jugador");

        
        for (Object it: columnas) {
            modelo.addColumn(it);
        }
        jtJugadores.setModel(modelo);
    }
    
    public void cargarTorneos() {
        
        for(Torneo item: listaTorneos) {
            jcbTorneo.addItem(item);
        }
    } 
     public void borrarFilasTabla() {
        int a = modelo.getRowCount()-1;
        
        for(int i=a; i>=0; i--) {
            modelo.removeRow(i);
        }
    }
      public void cargarDatos() {
          
        borrarFilasTabla();
        
        Torneo t = (Torneo)jcbTorneo.getSelectedItem();
        listaJugadores = (ArrayList)tor.listaJugadoresXTorneo(t.getId_torneo());

        for (Jugador j: listaJugadores){
            modelo.addRow(new Object[] {j.getId_jugador(), j.getNombreApellido()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbTorneo = new javax.swing.JComboBox<>();
        jlTorneo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtJugadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jcbTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTorneoActionPerformed(evt);
            }
        });

        jlTorneo.setText("Torneo");

        jtJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtJugadores.setEnabled(false);
        jScrollPane1.setViewportView(jtJugadores);

        jLabel1.setText("Jugadores por Torneo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jlTorneo)
                        .addGap(27, 27, 27)
                        .addComponent(jcbTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTorneo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTorneoActionPerformed
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jcbTorneoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Torneo> jcbTorneo;
    private javax.swing.JLabel jlTorneo;
    private javax.swing.JTable jtJugadores;
    // End of variables declaration//GEN-END:variables
}
