/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneoTenis_Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import torneoTenis_Data.JugadorData;
import torneoTenis_Data.PatrocinioData;
import torneoTenis_Data.SponsorData;
import torneotenis.Conectar;
import torneotenis.Jugador;
import torneotenis.Patrocinio;
import torneotenis.Sponsor;

/**
 *
 * @author Administrador
 */
public class VistaSponsorsXJugador extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private Conectar conn;
    private JugadorData jugador;
    private PatrocinioData pat;
    private SponsorData sponsor;
    private ArrayList<Jugador> listaJugadores;
    private ArrayList<Sponsor> listaSponsor;

    /**
     * Creates new form VistaSponsorsXJugador
     */
    public VistaSponsorsXJugador() {
        initComponents();
        conn = new Conectar();
        jugador = new JugadorData(conn);
        sponsor = new SponsorData(conn);
        pat = new PatrocinioData(conn);
        Patrocinio p = new Patrocinio();
        listaJugadores = (ArrayList) jugador.listaDeJugadores();
        
        armarCabeceraTabla();
        cargarJugadores();
        cargarDatos();
    }
    
    public void armarCabeceraTabla() {
        jtSponsors.getTableHeader().setReorderingAllowed(false);
        
        ArrayList<Object> columnas = new ArrayList<Object>();
        
        columnas.add("ID");
        columnas.add("Marca");
        columnas.add("Indumentaria");

        
        for (Object it: columnas) {
            modelo.addColumn(it);
        }
        jtSponsors.setModel(modelo);
    }
    
    public void cargarJugadores() {
        
        for(Jugador item: listaJugadores) {
            jcbJugador.addItem(item);
        }
    } 
     public void borrarFilasTabla() {
        int a = modelo.getRowCount()-1;
        
        for(int i=a; i>=0; i--) {
            modelo.removeRow(i);
        }
    }
     
    public void cargarDatos() {
          
        borrarFilasTabla();
        
        Jugador j = (Jugador)jcbJugador.getSelectedItem();
        listaSponsor = (ArrayList)pat.obtenerSponsorXJugador(j.getId_jugador());

        for (Sponsor s: listaSponsor){
            modelo.addRow(new Object[] {s.getId_sponsor(), s.getMarca(), s.getIndumentaria()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbJugador = new javax.swing.JComboBox<>();
        jlJugador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSponsors = new javax.swing.JTable();
        jlTitulo4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jcbJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbJugadorActionPerformed(evt);
            }
        });

        jlJugador.setText("Jugador");

        jtSponsors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtSponsors);

        jlTitulo4.setText("Sponsors por Jugador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jlJugador)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo4)
                            .addComponent(jcbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo4)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlJugador))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbJugadorActionPerformed
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jcbJugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Jugador> jcbJugador;
    private javax.swing.JLabel jlJugador;
    private javax.swing.JLabel jlTitulo4;
    private javax.swing.JTable jtSponsors;
    // End of variables declaration//GEN-END:variables
}
