/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneoTenis_Vistas;

/**
 *
 * @author Administrador
 */
public class VistasGeneral extends javax.swing.JFrame {

    /**
     * Creates new form VistasGeneral
     */
    public VistasGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esc = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        jmCarga = new javax.swing.JMenu();
        jmJugador = new javax.swing.JMenuItem();
        jmEstadio = new javax.swing.JMenuItem();
        jmTorneo = new javax.swing.JMenuItem();
        jmSponsor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escLayout = new javax.swing.GroupLayout(esc);
        esc.setLayout(escLayout);
        escLayout.setHorizontalGroup(
            escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escLayout.setVerticalGroup(
            escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jmCarga.setText("Carga de Datos");

        jmJugador.setText("Jugador");
        jmJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJugadorActionPerformed(evt);
            }
        });
        jmCarga.add(jmJugador);

        jmEstadio.setText("Estadio");
        jmEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEstadioActionPerformed(evt);
            }
        });
        jmCarga.add(jmEstadio);

        jmTorneo.setText("Torneo");
        jmCarga.add(jmTorneo);

        jmSponsor.setText("Sponsor");
        jmCarga.add(jmSponsor);

        jMenu.add(jmCarga);

        jMenu2.setText("Salir");
        jMenu.add(jMenu2);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esc)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEstadioActionPerformed
        // TODO add your handling code here:
          esc.removeAll();
          esc.repaint();
          VistaEstadio ve = new VistaEstadio();
          ve.setVisible(true);
          esc.add(ve);
          esc.moveToFront(ve);
        
    }//GEN-LAST:event_jmEstadioActionPerformed

    private void jmJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJugadorActionPerformed
        // TODO add your handling code here:
          esc.removeAll();
          esc.repaint();
          VistaJugador vj = new VistaJugador();
          vj.setVisible(true);
          esc.add(vj);
          esc.moveToFront(vj);
    }//GEN-LAST:event_jmJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistasGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane esc;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jmCarga;
    private javax.swing.JMenuItem jmEstadio;
    private javax.swing.JMenuItem jmJugador;
    private javax.swing.JMenuItem jmSponsor;
    private javax.swing.JMenuItem jmTorneo;
    // End of variables declaration//GEN-END:variables
}
