/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneoTenis_Vistas;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import torneoTenis_Data.EncuentrosData;
import torneoTenis_Data.EstadioData;
import torneoTenis_Data.JugadorData;
import torneoTenis_Data.TorneoData;
import torneotenis.Conectar;
import torneotenis.Encuentros;
import torneotenis.Estadio;
import torneotenis.Jugador;
import torneotenis.Torneo;

/**
 *
 * @author Familia
 */
public class VistaEncuentros extends javax.swing.JInternalFrame {
    private TorneoData torneoData;
    private Conectar conn;
    private JugadorData jugadorData;
    private EstadioData estadioData;
    private EncuentrosData encuentrosData;
    //private Encuentros enc;

    /**
     * Creates new form VistaRanking
     */
    public VistaEncuentros() {
        initComponents();
        conn = new Conectar();
        torneoData = new TorneoData(conn);
        estadioData = new EstadioData(conn);
        jugadorData = new JugadorData(conn);
        encuentrosData = new EncuentrosData(conn);
        Torneo t = new Torneo();
        
        cargarDatosTorneos();
        cargarDatosJugadores();
        cargarDatosEstadios();
    }
    
    public void cargarDatosJugadores() {
        List <Jugador> jugadores = jugadorData.listaDeJugadores();
        for(Jugador j: jugadores){
            jcbJug1.addItem(j);
            jcbJug2.addItem(j);
        }
    }
    public void cargarDatosGanador(){
        int id = Integer.parseInt(jtId.getText());
        Encuentros enc = encuentrosData.buscarEncuentro(id);
        List <Jugador> jugadores = encuentrosData.listaPosibleGanador(id);
        for(Jugador j: jugadores){
        jcbGanador.addItem(j);
    }}
     public void cargarDatosTorneos() {
        List <Torneo> torneos = torneoData.listaDeTorneos();
        for(Torneo t: torneos){
            jcbTorneo.addItem(t);     
        }
    }
     public void cargarDatosEstadios() {
        List <Estadio> est = estadioData.listaDeEstadios();
        for(Estadio e: est){
            jcbEst.addItem(e);     
        }
    }
     public void borrarCombo() {
        int a = jcbEst.getSelectedIndex()-1;
        for (int i=a; i>=0; i--){
            jcbEst.removeAllItems();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jchbActivo = new javax.swing.JCheckBox();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jcbJug2 = new javax.swing.JComboBox<>();
        jcbJug1 = new javax.swing.JComboBox<>();
        jcbEst = new javax.swing.JComboBox<>();
        jcbTorneo = new javax.swing.JComboBox<>();
        jtId = new javax.swing.JTextField();
        jcEstado = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jcbGanador = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ENCUENTROS");

        jLabel2.setText("N° Encuentro:");

        jLabel3.setText("Fecha Encuentro:");

        jLabel4.setText("Estado:");

        jLabel5.setText("Ganador:");

        jLabel6.setText("Jugador 1:");

        jLabel7.setText("Jugador 2:");

        jLabel8.setText("Estadio:");

        jLabel9.setText("Torneo:");

        jLabel10.setText("Activo");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jchbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbActivoActionPerformed(evt);
            }
        });

        jdcFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jdcFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdcFechaFocusLost(evt);
            }
        });
        jdcFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jdcFechaMouseExited(evt);
            }
        });

        jcbJug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbJug2ActionPerformed(evt);
            }
        });

        jcbJug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbJug1ActionPerformed(evt);
            }
        });

        jcbEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstActionPerformed(evt);
            }
        });

        jcbTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTorneoActionPerformed(evt);
            }
        });

        jtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtIdFocusLost(evt);
            }
        });

        jcEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcEstadoFocusLost(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jcbGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGanadorActionPerformed(evt);
            }
        });

        jLabel11.setText("1. Por jugarse \n2. En Curso \n3. Finalizado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jbGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbActualizar)
                                .addGap(57, 57, 57)
                                .addComponent(jbEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jchbActivo)
                                        .addGap(276, 276, 276))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(286, 286, 286)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel3))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jbLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbGanador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbEst, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbJug1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jcbJug2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 195, Short.MAX_VALUE)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbBuscar)
                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jcbJug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jcbTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbGuardar)
                            .addComponent(jbActualizar)
                            .addComponent(jbEliminar)
                            .addComponent(jbLimpiar)))
                    .addComponent(jchbActivo))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbJug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbJug1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jcbJug1ActionPerformed

    private void jchbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchbActivoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
 
        int estadoEnCurso=Integer.parseInt(jcEstado.getText());
        
        
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = formato.format(jdcFecha.getDate());
        LocalDate fechaEnc=LocalDate.parse(fecha, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        
        Jugador jugador1 = (Jugador) jcbJug1.getSelectedItem();
        Jugador jugador2 = (Jugador) jcbJug2.getSelectedItem();
        Estadio estadio = (Estadio) jcbEst.getSelectedItem();
        Torneo torneo = (Torneo) jcbTorneo.getSelectedItem();
        boolean activo=jchbActivo.isEnabled();
        LocalDate fechaEncIni = torneo.getFecha_ini();
        LocalDate fechaEncFi = torneo.getFecha_fin();
        
        try {

            if (fechaEnc.isBefore(fechaEncIni) || fechaEnc.isAfter(fechaEncFi)){
                JOptionPane.showMessageDialog(this, "La fecha del encuentro no esta en el rango del torneo, fecha inicio: "+fechaEncIni+" y fecha fin: "+fechaEncFi);
            }
            if(estadoEnCurso < 1 || estadoEnCurso > 3){
                JOptionPane.showMessageDialog(this, "Valor de Estado incorrecto");}
            else {
                 Encuentros enc = new Encuentros(fechaEnc, estadoEnCurso, jugador1, jugador2, estadio, torneo, activo);
               encuentrosData.guardarEncuentros(enc);
                jtId.setText(enc.getId_encuentro() + "");
            }
                
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Usted ingresó mal la fecha");  
        }  
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        if(jtId.getText()!=null){
        int id_encuentro = Integer.parseInt(jtId.getText());
        int estadoEnCurso=Integer.parseInt(jcEstado.getText());
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = formato.format(jdcFecha.getDate());
        LocalDate fechaEnc=LocalDate.parse(fecha, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        
        Jugador jugador1 = (Jugador) jcbJug1.getSelectedItem();
        Jugador jugador2 = (Jugador) jcbJug2.getSelectedItem();
        Jugador ganador = (Jugador) jcbGanador.getSelectedItem();
        Estadio estadio = (Estadio) jcbEst.getSelectedItem();
        Torneo torneo = (Torneo) jcbTorneo.getSelectedItem();
        boolean activo=jchbActivo.isEnabled();
        
        LocalDate fechaEncIni = torneo.getFecha_ini();
        LocalDate fechaEncFi = torneo.getFecha_fin();
        
        try {

            if (fechaEnc.isBefore(fechaEncIni) || fechaEnc.isAfter(fechaEncFi)){
                JOptionPane.showMessageDialog(this, "La fecha del encuentro no esta en el rango del torneo, fecha inicio: "+fechaEncIni+" y fecha fin: "+fechaEncFi);
            }
            else {
                 Encuentros enc = new Encuentros(id_encuentro, fechaEnc, estadoEnCurso, ganador, jugador1, jugador2, estadio, torneo, activo);
               encuentrosData.actualizarEncuentro(enc);
            }
                
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Usted ingresó mal la fecha");  
        }  
        }
        else {
            JOptionPane.showMessageDialog(this,"No se encontraron datos");
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jtId.getText());
        encuentrosData.borrarEncuentro(id);
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        jtId.setText("");
        jcEstado.setText("");
        jdcFecha.setDate(null);
        jchbActivo.setSelected(false);
        jcbGanador.setSelectedIndex(-1);
        jcbJug1.setSelectedIndex(-1);
        jcbJug2.setSelectedIndex(-1);
        jcbEst.setSelectedIndex(-1);
        jcbTorneo.setSelectedIndex(-1);
        
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(jtId.getText());
        Encuentros enc = encuentrosData.buscarEncuentro(id);
       
        if(enc != null) {
           
            jtId.setText(enc.getId_encuentro()+"");
            jcEstado.setText(enc.getEstadoEnCurso()+"");
            jdcFecha.setDate(Date.valueOf(enc.getFechaEnc()));
            jcbJug1.setSelectedItem(enc.getJugador1());
            jcbJug2.setSelectedItem(enc.getJugador2());
            jcbGanador.setSelectedItem(enc.getGanador());
            jcbEst.setSelectedItem(enc.getEstadio());
            jcbTorneo.setSelectedItem(enc.getTorneo());
            jchbActivo.setSelected(enc.isActivo());
            cargarDatosGanador();
        }else{
            JOptionPane.showMessageDialog(this,"No se encontraron datos");
        }      
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jcbJug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbJug2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbJug2ActionPerformed

    private void jcbEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jcbEstActionPerformed

    private void jcbTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTorneoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbTorneoActionPerformed

    private void jcbGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGanadorActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jcbGanadorActionPerformed

    private void jtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtIdFocusLost
        // TODO add your handling code here:
       // try {
            //int enc = Integer.parseInt(jtId.getText());
        //} catch (NumberFormatException nf) {
         //   JOptionPane.showMessageDialog(this, "Usted ingresó un digito incorrecto");
         //   jtId.requestFocus();
        //}
    }//GEN-LAST:event_jtIdFocusLost

    private void jdcFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcFechaFocusLost
        // TODO add your handling code here:
        Torneo torneo = (Torneo) jcbTorneo.getSelectedItem();
        
        LocalDate fechaEncIni = torneo.getFecha_ini();
        //Date fechaEncIn = (Date) Date.from(fechaEncIni.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        LocalDate fechaEncFi = torneo.getFecha_fin();
        //Date fechaFi = (Date) Date.from(fechaEncFi.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        System.out.println(fechaEncFi);
        try {
           SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
           String fecha = formato.format(jdcFecha.getDate());
           LocalDate fechaEnc=LocalDate.parse(fecha, DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            if (fechaEnc.isBefore(fechaEncIni) || fechaEnc.isAfter(fechaEncFi)){
                JOptionPane.showMessageDialog(this, "La fecha del encuentro no esta en el rango del torneo, fecha inicio: "+fechaEncIni+" y fecha fin: "+fechaEncFi);
            }
            else {
                System.out.println("Error");
            }
                
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Usted ingresó mal la fecha");
            jdcFecha.requestFocus();
        }
    }//GEN-LAST:event_jdcFechaFocusLost

    private void jdcFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdcFechaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jdcFechaMouseExited

    private void jdcFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcFechaFocusGained
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jdcFechaFocusGained

    private void jcEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcEstadoFocusLost
    
    }//GEN-LAST:event_jcEstadoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JTextField jcEstado;
    private javax.swing.JComboBox<Estadio> jcbEst;
    private javax.swing.JComboBox<Jugador> jcbGanador;
    private javax.swing.JComboBox<Jugador> jcbJug1;
    private javax.swing.JComboBox<Jugador> jcbJug2;
    private javax.swing.JComboBox<Torneo> jcbTorneo;
    private javax.swing.JCheckBox jchbActivo;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTextField jtId;
    // End of variables declaration//GEN-END:variables
}
