/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneoTenis_Vistas;

/**
 *
 * @author Administrador
 */
public class VistasGeneral extends javax.swing.JFrame {

    /**
     * Creates new form VistasGeneral
     */
    public VistasGeneral() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esc = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        jmCarga = new javax.swing.JMenu();
        jmJugador = new javax.swing.JMenuItem();
        jmEstadio = new javax.swing.JMenuItem();
        jmTorneo = new javax.swing.JMenuItem();
        jmSponsor = new javax.swing.JMenuItem();
        jmEncuentros = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmRanking = new javax.swing.JMenuItem();
        jmJugaTor = new javax.swing.JMenuItem();
        jmFutEnc = new javax.swing.JMenuItem();
        jmTorJug = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escLayout = new javax.swing.GroupLayout(esc);
        esc.setLayout(escLayout);
        escLayout.setHorizontalGroup(
            escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        escLayout.setVerticalGroup(
            escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jmCarga.setText("Carga de Datos");
        jmCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargaActionPerformed(evt);
            }
        });

        jmJugador.setText("Jugador");
        jmJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJugadorActionPerformed(evt);
            }
        });
        jmCarga.add(jmJugador);

        jmEstadio.setText("Estadio");
        jmEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEstadioActionPerformed(evt);
            }
        });
        jmCarga.add(jmEstadio);

        jmTorneo.setText("Torneo");
        jmTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTorneoActionPerformed(evt);
            }
        });
        jmCarga.add(jmTorneo);

        jmSponsor.setText("Sponsor");
        jmSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSponsorActionPerformed(evt);
            }
        });
        jmCarga.add(jmSponsor);

        jmEncuentros.setText("Encuentros");
        jmEncuentros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEncuentrosActionPerformed(evt);
            }
        });
        jmCarga.add(jmEncuentros);

        jMenu.add(jmCarga);

        jmConsultas.setText("Consultas");

        jmRanking.setText("Ranking");
        jmRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRankingActionPerformed(evt);
            }
        });
        jmConsultas.add(jmRanking);

        jmJugaTor.setText("Jugadores por torneo");
        jmJugaTor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJugaTorActionPerformed(evt);
            }
        });
        jmConsultas.add(jmJugaTor);

        jmFutEnc.setText("Futuros Encuentros");
        jmFutEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFutEncActionPerformed(evt);
            }
        });
        jmConsultas.add(jmFutEnc);

        jmTorJug.setText("Torneos por jugador");
        jmTorJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTorJugActionPerformed(evt);
            }
        });
        jmConsultas.add(jmTorJug);

        jMenu.add(jmConsultas);

        jMenu2.setText("Salir");
        jMenu.add(jMenu2);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esc)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEstadioActionPerformed
        // TODO add your handling code here:
          esc.removeAll();
          esc.repaint();
          VistaEstadio ve = new VistaEstadio();
          ve.setVisible(true);
          esc.add(ve);
          esc.moveToFront(ve);
        
    }//GEN-LAST:event_jmEstadioActionPerformed

    private void jmJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJugadorActionPerformed
        // TODO add your handling code here:
          esc.removeAll();
          esc.repaint();
          VistaJugador vj = new VistaJugador();
          vj.setVisible(true);
          esc.add(vj);
          esc.moveToFront(vj);
    }//GEN-LAST:event_jmJugadorActionPerformed

    private void jmCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCargaActionPerformed

    private void jmTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTorneoActionPerformed
        // TODO add your handling code here:
         esc.removeAll();
         esc.repaint();
         VistaTorneo vt = new VistaTorneo();
          vt.setVisible(true);
          esc.add(vt);
          esc.moveToFront(vt);
    }//GEN-LAST:event_jmTorneoActionPerformed

    private void jmSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSponsorActionPerformed
        // TODO add your handling code here:
         esc.removeAll();
         esc.repaint();
         VistaSponsorPatrocinio vs = new VistaSponsorPatrocinio();
         vs.setVisible(true);
         esc.add(vs);
         esc.moveToFront(vs);
    }//GEN-LAST:event_jmSponsorActionPerformed

    private void jmRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRankingActionPerformed
        // TODO add your handling code here:
        esc.removeAll();
        esc.repaint();
        VistaRanking vs = new VistaRanking();
        vs.setVisible(true);
        esc.add(vs);
        esc.moveToFront(vs);
    }//GEN-LAST:event_jmRankingActionPerformed

    private void jmEncuentrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEncuentrosActionPerformed
        // TODO add your handling code here:
        esc.removeAll();
        esc.repaint();
        VistaEncuentros ven = new VistaEncuentros();
        ven.setVisible(true);
        esc.add(ven);
        esc.moveToFront(ven);
    }//GEN-LAST:event_jmEncuentrosActionPerformed

    private void jmFutEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFutEncActionPerformed
        // TODO add your handling code here:
        esc.removeAll();
        esc.repaint();
        VistaFuturosEncuentros vfe = new VistaFuturosEncuentros();
        vfe.setVisible(true);
        esc.add(vfe);
        esc.moveToFront(vfe);
    }//GEN-LAST:event_jmFutEncActionPerformed

    private void jmJugaTorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJugaTorActionPerformed
        // TODO add your handling code here:
        esc.removeAll();
        esc.repaint();
        VistaJugadoresXTorneo vjt = new VistaJugadoresXTorneo();
        vjt.setVisible(true);
        esc.add(vjt);
        esc.moveToFront(vjt);
    }//GEN-LAST:event_jmJugaTorActionPerformed

    private void jmTorJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTorJugActionPerformed
        // TODO add your handling code here:
        esc.removeAll();
        esc.repaint();
        VistaTorneosXJugador vtj = new VistaTorneosXJugador();
        vtj.setVisible(true);
        esc.add(vtj);
        esc.moveToFront(vtj);
    }//GEN-LAST:event_jmTorJugActionPerformed
                      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistasGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane esc;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jmCarga;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmEncuentros;
    private javax.swing.JMenuItem jmEstadio;
    private javax.swing.JMenuItem jmFutEnc;
    private javax.swing.JMenuItem jmJugaTor;
    private javax.swing.JMenuItem jmJugador;
    private javax.swing.JMenuItem jmRanking;
    private javax.swing.JMenuItem jmSponsor;
    private javax.swing.JMenuItem jmTorJug;
    private javax.swing.JMenuItem jmTorneo;
    // End of variables declaration//GEN-END:variables
}
